### ISSUE TITLE
READ ME

### ISSUE THREAD

**Issue by MaximusAlmeida** [Aerakor/TWM#11]
@Arkagaen, I won't be active for the next week or so, because I am going on vacation. I will be back on Tuesday, so I should start to be active again on Wednesday or Thursday.

**Comment by Arkagaen** [comment]
Ok, but you know while GitHub isn't meant for chatting, aerakor is.

**Comment by Arkagaen** [comment]
Have a nice trip :)

**Comment by MaximusAlmeida** [comment]
Thanks, and for the chatting thing. I forgot sorry.
