### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by Arkagaen** [Aerakor/TWM#12]
I don't like this setup.
The Pre-week is fine, but the other weeks should be as follows:
Instead of being: tw.mp.aerakor.com/Weekly Programs/twm1.html
It needs to be: tw.mp.aerakor.com/week/1/index.html

I'm not changing it because these changes need to be made by you.
In short, change "Weekly Programs" to "week"
Add a folder "1"
in the folder put all the week's files.
Rename twm1.html to index.html

**Comment by MP-MaximusPrime** [comment]
Okay

**Comment by MP-MaximusPrime** [comment]
Do you know what this week's thing is?

**Comment by MP-MaximusPrime** [comment]
It's a password/username thing made by js

**Comment by MP-MaximusPrime** [comment]
`var a=true`

**Comment by Arkagaen** [comment]
'var b=false'

**Comment by Arkagaen** [comment]
Whoops

**Comment by MP-MaximusPrime** [comment]
Go to aerakor

**Comment by MP-MaximusPrime** [comment]
Think I have fixed it
